install:
- cmd: nuget restore
build_script:
- cmd: |
    msbuild "C:\projects\multipletestssamename\MultipleTestsSameName.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release
    msbuild "C:\projects\multipletestssamename\MultipleTestsSameName.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Debug
